package Frames;

import DAO.DAO_Genero;
import Objetos.Genero;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author Manutenção
 */
public class fr_Genero extends javax.swing.JFrame {

    DAO_Genero dao = new DAO_Genero();
    Genero linha;

    private String operacao;

    public fr_Genero() {
        initComponents();
        Habilitar(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_Salvar = new javax.swing.JButton();
        bt_Salvar2 = new javax.swing.JButton();
        lb_codigo = new javax.swing.JLabel();
        lb_desc = new javax.swing.JLabel();
        lb_Abr = new javax.swing.JLabel();
        tf_Codigo = new javax.swing.JTextField();
        tf_Descricao = new javax.swing.JTextField();
        tf_Abreviatura = new javax.swing.JTextField();
        bt_Limpar = new javax.swing.JButton();
        bt_Relatorio = new javax.swing.JButton();
        bt_Alterar = new javax.swing.JButton();
        bt_Incluir1 = new javax.swing.JButton();
        bt_Salvar1 = new javax.swing.JButton();
        bt_Excluir = new javax.swing.JButton();

        bt_Salvar.setText("Salvar");

        bt_Salvar2.setText("Salvar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manutenção de Genero de Pessoas");

        lb_codigo.setText("Código:");

        lb_desc.setText("Descrição:");

        lb_Abr.setText("Abreviatura:");

        tf_Codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_CodigoFocusLost(evt);
            }
        });

        bt_Limpar.setText("Limpar");
        bt_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LimparActionPerformed(evt);
            }
        });

        bt_Relatorio.setText("Relatório");
        bt_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RelatorioActionPerformed(evt);
            }
        });

        bt_Alterar.setText("Alterar");
        bt_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AlterarActionPerformed(evt);
            }
        });

        bt_Incluir1.setText("Incluir");
        bt_Incluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Incluir1ActionPerformed(evt);
            }
        });

        bt_Salvar1.setText("Salvar");
        bt_Salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Salvar1ActionPerformed(evt);
            }
        });

        bt_Excluir.setText("Excluir");
        bt_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_Abr)
                            .addComponent(lb_desc)
                            .addComponent(lb_codigo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Abreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Relatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Incluir1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_Salvar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Excluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_codigo)
                    .addComponent(tf_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_desc)
                    .addComponent(tf_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Abr)
                    .addComponent(tf_Abreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar)
                    .addComponent(bt_Relatorio)
                    .addComponent(bt_Alterar)
                    .addComponent(bt_Incluir1)
                    .addComponent(bt_Salvar1)
                    .addComponent(bt_Excluir))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_LimparActionPerformed

    private void bt_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RelatorioActionPerformed
        fr_GeneroRelatorioGeralGenero fr_RelGeral = new fr_GeneroRelatorioGeralGenero();

        fr_RelGeral.setVisible(true);
    }//GEN-LAST:event_bt_RelatorioActionPerformed

    private void bt_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AlterarActionPerformed
        tf_Codigo.setEnabled(true);
        operacao = "A";

    }//GEN-LAST:event_bt_AlterarActionPerformed

    private void tf_CodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_CodigoFocusLost

        try {
            int Codigo = Integer.parseInt((tf_Codigo.getText().trim()));

            MontaTela(Codigo);

            if (operacao.equals("E")) {
                int resp = JOptionPane.showConfirmDialog(null, "Confirma Exclusão?", "Confirmação", JOptionPane.YES_NO_CANCEL_OPTION);

                if (resp == 0) {
                    Exclusao(Codigo);
                }
                Limpar();
            }

            if (operacao.equals("A")) {
                Habilitar(true);
                tf_Codigo.setEnabled(false);

            }

        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(null, "Informe o Código Corretamente", "Erro", JOptionPane.ERROR_MESSAGE);
            Limpar();
        }


    }//GEN-LAST:event_tf_CodigoFocusLost

    private void bt_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ExcluirActionPerformed
        tf_Codigo.setEnabled(true);
        operacao = "E";
    }//GEN-LAST:event_bt_ExcluirActionPerformed

    private void bt_Salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Salvar1ActionPerformed

        if (ConsisteCampos()) {

            if (operacao.equals("I")) {

                try {
                    if (dao.incluir_Genero(linha)) {
                        JOptionPane.showMessageDialog(null, "Registro Incluido com sucesso", "Messagem", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Registro NÃO foi Incluido.", "Erro dados", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (Exception erro) {
                    JOptionPane.showMessageDialog(null, "Erro ao Incluir  Registro. BD." + erro.getMessage(), "Erro BD", JOptionPane.ERROR_MESSAGE);
                } finally {
                    Limpar();
                }

            }

            if (operacao.equals("A")) {

                try {

                    if (dao.altera_Genero(linha)) {
                        JOptionPane.showMessageDialog(null, "Registro Alterado com sucesso", "Messagem", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Registro NÃO foi Alterado.", "Erro dados", JOptionPane.ERROR_MESSAGE);
                    }

                } catch (Exception erro) {
                    JOptionPane.showMessageDialog(null, "Erro ao Alterar Registro. BD." + erro.getMessage(), "Erro BD", JOptionPane.ERROR_MESSAGE);
                } finally {
                    Limpar();
                }

            }

        } else {

            JOptionPane.showMessageDialog(null, "Informe todos os Campos.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_bt_Salvar1ActionPerformed

    private void bt_Incluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Incluir1ActionPerformed
        operacao = "I";
        tf_Abreviatura.setEnabled(true);
        tf_Descricao.setEnabled(true);
    }//GEN-LAST:event_bt_Incluir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Genero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Alterar;
    private javax.swing.JButton bt_Excluir;
    private javax.swing.JButton bt_Incluir1;
    private javax.swing.JButton bt_Limpar;
    private javax.swing.JButton bt_Relatorio;
    private javax.swing.JButton bt_Salvar;
    private javax.swing.JButton bt_Salvar1;
    private javax.swing.JButton bt_Salvar2;
    private javax.swing.JLabel lb_Abr;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lb_desc;
    private javax.swing.JTextField tf_Abreviatura;
    private javax.swing.JTextField tf_Codigo;
    private javax.swing.JTextField tf_Descricao;
    // End of variables declaration//GEN-END:variables

    private boolean ConsisteCampos() {

        boolean saida = true;
        String msg = "";

        if ((!tf_Descricao.getText().trim().isEmpty())
                && (!tf_Abreviatura.getText().trim().isEmpty())) {

            linha = new Genero();

            msg = linha.is_ds_GeneroValido(tf_Descricao.getText().trim());
            if (!msg.isEmpty()) {
                JOptionPane.showMessageDialog(null, msg, "Erro", JOptionPane.ERROR_MESSAGE);
                saida = false;
            }

            msg = linha.is_abr_GeneroValido(tf_Abreviatura.getText().trim());
            if (!msg.isEmpty()) {
                JOptionPane.showMessageDialog(null, msg, "Erro", JOptionPane.ERROR_MESSAGE);
                saida = false;

            }

            if (saida) {
                linha.setDs_genero(tf_Descricao.getText().trim());
                linha.setAbr_Genero(tf_Abreviatura.getText().trim());

                if (operacao.equals("A")) {
                    linha.setCd_genero(Integer.parseInt(tf_Codigo.getText().trim()));
                }
            }

        } else {
            saida = false;
        }

        return saida;
    }

    private void Limpar() {
        tf_Abreviatura.setText(null);
        tf_Codigo.setText(null);
        tf_Descricao.setText(null);
        Habilitar(false);
        operacao = "";
    }

    private void Habilitar(boolean arg) {
        tf_Abreviatura.setEnabled(arg);
        tf_Codigo.setEnabled(arg);
        tf_Descricao.setEnabled(arg);
        //operacao = "";
    }

    private void MontaTela(int cod) {

        linha = new Genero();
        try {
            linha = dao.Consulta_Genero_Unitaria(cod);

            tf_Codigo.setText(String.valueOf(linha.getCd_genero()));
            tf_Descricao.setText(linha.getDs_genero());
            tf_Abreviatura.setText(linha.getAbr_Genero());

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro na Montagem tela - Acesso a BD\n" + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void Exclusao(int cod) {

        try {
            boolean saida = dao.exclui_Genero(cod);
            if (saida) {
                JOptionPane.showMessageDialog(null, "Exclusão Concluída com sucesso!", "Mensagem", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão não Concluída. Verifique.", "Mensagem", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro na Exclusão - Acesso a BD\n" + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void Alterar() {

    } // fim Alterar()

}
