/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author FO
 */
public class fr_Cad_Cidade extends javax.swing.JFrame {

    private Tab_Cidade tab_cidade;
    private fr_Relatorio_Cidade local_fr_Relatorio_Cidade;

    private ArrayList<Tab_Cidade> lista_tab_cidade = new ArrayList();

    private int cod;

    /**
     * Creates new form fr_Cad_Cidade
     */
    public fr_Cad_Cidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cd_Cidade = new javax.swing.JLabel();
        tf_cd_Cidade = new javax.swing.JTextField();
        lb_nm_Cidade = new javax.swing.JLabel();
        tf_nm_Cidade = new javax.swing.JTextField();
        lb_abr_Cidade = new javax.swing.JLabel();
        tf_abr_Cidade = new javax.swing.JTextField();
        lb_uf_Cidade = new javax.swing.JLabel();
        bt_Limpar_Cidade = new javax.swing.JButton();
        lb_valida_Cidade = new javax.swing.JButton();
        bt_Relatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cidade");

        lb_cd_Cidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_cd_Cidade.setText("Código:");

        lb_nm_Cidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_nm_Cidade.setText("Nome:");

        lb_abr_Cidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_abr_Cidade.setText("Abreviatura:");

        lb_uf_Cidade.setText("UF: (FK)");

        bt_Limpar_Cidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_Limpar_Cidade.setText("Limpar");
        bt_Limpar_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Limpar_CidadeActionPerformed(evt);
            }
        });

        lb_valida_Cidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_valida_Cidade.setText("Valida");
        lb_valida_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_valida_CidadeActionPerformed(evt);
            }
        });

        bt_Relatorio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_Relatorio.setText("Relatório");
        bt_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_Limpar_Cidade)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lb_abr_Cidade)
                                .addComponent(lb_nm_Cidade)
                                .addComponent(lb_cd_Cidade)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(lb_uf_Cidade))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_cd_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nm_Cidade, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(tf_abr_Cidade)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lb_valida_Cidade)
                        .addGap(28, 28, 28)
                        .addComponent(bt_Relatorio)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cd_Cidade)
                    .addComponent(tf_cd_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nm_Cidade)
                    .addComponent(tf_nm_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_abr_Cidade)
                    .addComponent(tf_abr_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_uf_Cidade)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar_Cidade)
                    .addComponent(lb_valida_Cidade)
                    .addComponent(bt_Relatorio))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Limpar_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Limpar_CidadeActionPerformed

        LimparCampos();

    }//GEN-LAST:event_bt_Limpar_CidadeActionPerformed

    private void lb_valida_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_valida_CidadeActionPerformed
        
        Carrega_TabCidade();
        if (Validacao()) {

            LimparCampos();

        }
    }//GEN-LAST:event_lb_valida_CidadeActionPerformed

    private void bt_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RelatorioActionPerformed
        if (!lista_tab_cidade.isEmpty()) {

            local_fr_Relatorio_Cidade = new fr_Relatorio_Cidade();
            local_fr_Relatorio_Cidade.MontaRelatorio_Cidade(lista_tab_cidade);
            local_fr_Relatorio_Cidade.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(null, "Sem Registros para Exibir", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_RelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Cidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Cidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Cidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Cidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Cad_Cidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Limpar_Cidade;
    private javax.swing.JButton bt_Relatorio;
    private javax.swing.JLabel lb_abr_Cidade;
    private javax.swing.JLabel lb_cd_Cidade;
    private javax.swing.JLabel lb_nm_Cidade;
    private javax.swing.JLabel lb_uf_Cidade;
    private javax.swing.JButton lb_valida_Cidade;
    private javax.swing.JTextField tf_abr_Cidade;
    private javax.swing.JTextField tf_cd_Cidade;
    private javax.swing.JTextField tf_nm_Cidade;
    // End of variables declaration//GEN-END:variables

    private boolean validaCodCidade() {
        boolean saida = true;

        try {
            cod = Integer.parseInt(tf_cd_Cidade.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros para CÓDIGO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private boolean validaNomeCidade() {
        boolean saida = true;

        if (tf_nm_Cidade.getText().trim().length() < 4) {
            saida = false;
        }

        return saida;
    }

    private boolean validaAbrCidade() {
        boolean saida = true;
        if ((tf_abr_Cidade.getText().trim().length() < 3) || (tf_abr_Cidade.getText().trim().length() > 3)) {
            saida = false;
        }
        return saida;

    }

    private void Carrega_TabCidade() {

        try {
            cod = Integer.parseInt(tf_cd_Cidade.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros em CÓDIGO. ", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        tab_cidade = new Tab_Cidade();

        tab_cidade.setCod_cidade(cod);

        tab_cidade.setNm_cidade(tf_nm_Cidade.getText().trim());

        tab_cidade.setAbr_cidade(tf_abr_Cidade.getText().trim());

    }

    private boolean Validacao() {
        boolean saida = true;

        try {

            if (!validaCodCidade()) {
                throw new Exception("Digite apenas valores Inteiros para CÓDIGO.");

            }

            if (!validaNomeCidade()) {
                throw new Exception("O NOME tem que ter no minimo 4 caracteres!!!");
            }

            if (!validaAbrCidade()) {
                throw new Exception("A ABREVIATURA tem que ter 3 caracteres!!!");
            }
            lista_tab_cidade.add(tab_cidade);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de Validação de Campos: " + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private void LimparCampos() {

        tf_cd_Cidade.setText(null);
        tf_nm_Cidade.setText(null);
        tf_abr_Cidade.setText(null);

    }

}///////////////////////////////////////////
