/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author FO
 */
public class fr_Cad_GrauParentesco extends javax.swing.JFrame {

    private int cod;

    /**
     * Creates new form fr_Cad_GrauParentesco
     */
    public fr_Cad_GrauParentesco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cd_GrauParentesco = new javax.swing.JLabel();
        tf_cd_GrauParentesco = new javax.swing.JTextField();
        lb_ds_GrauParentesco = new javax.swing.JLabel();
        tf_ds_GrauParentesco = new javax.swing.JTextField();
        lb_nm_GrauParentesco = new javax.swing.JLabel();
        tf_nm_GrauParentesco = new javax.swing.JTextField();
        bt_Limpar_GrauParentesco = new javax.swing.JButton();
        bt_valida_GrauParentesco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadasro de Grau Parentesco");

        lb_cd_GrauParentesco.setText("Código:");

        lb_ds_GrauParentesco.setText("Descrição:");

        lb_nm_GrauParentesco.setText("Nome:");

        bt_Limpar_GrauParentesco.setText("Limpar");
        bt_Limpar_GrauParentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Limpar_GrauParentescoActionPerformed(evt);
            }
        });

        bt_valida_GrauParentesco.setText("Valida");
        bt_valida_GrauParentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_valida_GrauParentescoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_ds_GrauParentesco)
                            .addComponent(lb_cd_GrauParentesco)
                            .addComponent(lb_nm_GrauParentesco))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_ds_GrauParentesco, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(tf_nm_GrauParentesco)
                            .addComponent(tf_cd_GrauParentesco)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_Limpar_GrauParentesco)
                        .addGap(18, 18, 18)
                        .addComponent(bt_valida_GrauParentesco)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cd_GrauParentesco)
                    .addComponent(tf_cd_GrauParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ds_GrauParentesco)
                    .addComponent(tf_ds_GrauParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nm_GrauParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nm_GrauParentesco))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar_GrauParentesco)
                    .addComponent(bt_valida_GrauParentesco))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Limpar_GrauParentescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Limpar_GrauParentescoActionPerformed
        LimparCampos();
    }//GEN-LAST:event_bt_Limpar_GrauParentescoActionPerformed

    private void bt_valida_GrauParentescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_valida_GrauParentescoActionPerformed
        if (Validacao()) {

            LimparCampos();

        }
    }//GEN-LAST:event_bt_valida_GrauParentescoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_GrauParentesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_GrauParentesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_GrauParentesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_GrauParentesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Cad_GrauParentesco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Limpar_GrauParentesco;
    private javax.swing.JButton bt_valida_GrauParentesco;
    private javax.swing.JLabel lb_cd_GrauParentesco;
    private javax.swing.JLabel lb_ds_GrauParentesco;
    private javax.swing.JLabel lb_nm_GrauParentesco;
    private javax.swing.JTextField tf_cd_GrauParentesco;
    private javax.swing.JTextField tf_ds_GrauParentesco;
    private javax.swing.JTextField tf_nm_GrauParentesco;
    // End of variables declaration//GEN-END:variables

    private boolean validaCodGrauPar() {
        boolean saida = true;

        try {
            cod = Integer.parseInt(tf_cd_GrauParentesco.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros para CÓDIGO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private boolean validaNomeGrauPar() {
        boolean saida = true;

        if (tf_nm_GrauParentesco.getText().trim().length() < 4) {
            saida = false;
        }

        return saida;
    }

    private boolean validaDsGrauPar() {
        boolean saida = true;
        if ((tf_ds_GrauParentesco.getText().trim().length() < 3)) {
            saida = false;
        }
        return saida;

    }

    private boolean Validacao() {
        boolean saida = true;

        try {

            if (!validaCodGrauPar()) {
                throw new Exception("Digite apenas valores Inteiros para CÓDIGO.");

            }
            
            if (!validaDsGrauPar()) {
                throw new Exception("A DESCRIÇÃO tem que ter 3 caracteres!!!");
            }
            
            if (!validaNomeGrauPar()) {
                throw new Exception("O NOME tem que ter no minimo 4 caracteres!!!");
            }

            

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de Validação de Campos: " + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private void LimparCampos() {

        tf_cd_GrauParentesco.setText(null);
        tf_ds_GrauParentesco.setText(null);
        tf_nm_GrauParentesco.setText(null);

    }

}/////////////////////////////
