/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author FO
 */
public class fr_Cad_Dependente extends javax.swing.JFrame {

    private int cod;

    /**
     * Creates new form fr_Cad_Dependente
     */
    public fr_Cad_Dependente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cd_Dependente = new javax.swing.JLabel();
        tf_cd_Dependente = new javax.swing.JTextField();
        lb_func_Dependente = new javax.swing.JLabel();
        lb_nm_Dependente = new javax.swing.JLabel();
        tf_nm_Dependente = new javax.swing.JTextField();
        lb_dtn_Dependente = new javax.swing.JLabel();
        tf_dtn_Dependente = new javax.swing.JTextField();
        lb_rg_Dependente = new javax.swing.JLabel();
        tf_rg_Dependente = new javax.swing.JTextField();
        lb_cpf_Dependente = new javax.swing.JLabel();
        tf_cpf_Dependente = new javax.swing.JTextField();
        lb_gen_Dependente = new javax.swing.JLabel();
        lb_graupar_Dependente = new javax.swing.JLabel();
        bt_Limpar_Dependente = new javax.swing.JButton();
        bt_valida_Dependente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Dependente");

        lb_cd_Dependente.setText("Código:");

        lb_func_Dependente.setText("Dep. Funcionario: ( FK)");

        lb_nm_Dependente.setText("Nome:");

        lb_dtn_Dependente.setText("Data Nascimento:");

        lb_rg_Dependente.setText("RG:");

        lb_cpf_Dependente.setText("CPF:");

        lb_gen_Dependente.setText("Genero: (FK)");

        lb_graupar_Dependente.setText("Grau Parentesco: (FK)");

        bt_Limpar_Dependente.setText("Limpar");
        bt_Limpar_Dependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Limpar_DependenteActionPerformed(evt);
            }
        });

        bt_valida_Dependente.setText("Valida");
        bt_valida_Dependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_valida_DependenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_Limpar_Dependente)
                    .addComponent(lb_func_Dependente)
                    .addComponent(lb_cd_Dependente)
                    .addComponent(lb_nm_Dependente)
                    .addComponent(lb_dtn_Dependente)
                    .addComponent(lb_rg_Dependente)
                    .addComponent(lb_cpf_Dependente)
                    .addComponent(lb_gen_Dependente)
                    .addComponent(lb_graupar_Dependente))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nm_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_cd_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_dtn_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_rg_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_cpf_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bt_valida_Dependente)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cd_Dependente)
                    .addComponent(tf_cd_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_func_Dependente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nm_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nm_Dependente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dtn_Dependente)
                    .addComponent(tf_dtn_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_rg_Dependente)
                    .addComponent(tf_rg_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cpf_Dependente)
                    .addComponent(tf_cpf_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(lb_gen_Dependente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_graupar_Dependente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar_Dependente)
                    .addComponent(bt_valida_Dependente))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Limpar_DependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Limpar_DependenteActionPerformed
        tf_cd_Dependente.setText(null);
        tf_cpf_Dependente.setText(null);
        tf_dtn_Dependente.setText(null);
        tf_nm_Dependente.setText(null);
        tf_rg_Dependente.setText(null);
    }//GEN-LAST:event_bt_Limpar_DependenteActionPerformed

    private void bt_valida_DependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_valida_DependenteActionPerformed
        if (Validacao()) {

            LimparCampos();

        }
    }//GEN-LAST:event_bt_valida_DependenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Cad_Dependente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Limpar_Dependente;
    private javax.swing.JButton bt_valida_Dependente;
    private javax.swing.JLabel lb_cd_Dependente;
    private javax.swing.JLabel lb_cpf_Dependente;
    private javax.swing.JLabel lb_dtn_Dependente;
    private javax.swing.JLabel lb_func_Dependente;
    private javax.swing.JLabel lb_gen_Dependente;
    private javax.swing.JLabel lb_graupar_Dependente;
    private javax.swing.JLabel lb_nm_Dependente;
    private javax.swing.JLabel lb_rg_Dependente;
    private javax.swing.JTextField tf_cd_Dependente;
    private javax.swing.JTextField tf_cpf_Dependente;
    private javax.swing.JTextField tf_dtn_Dependente;
    private javax.swing.JTextField tf_nm_Dependente;
    private javax.swing.JTextField tf_rg_Dependente;
    // End of variables declaration//GEN-END:variables

    private boolean validaCodDependente() {
        boolean saida = true;

        try {
            cod = Integer.parseInt(tf_cd_Dependente.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros para CÓDIGO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private boolean validaNomeDependente() {
        boolean saida = true;

        if (tf_nm_Dependente.getText().trim().length() < 4) {
            saida = false;
        }

        return saida;
    }

    private boolean validaDtnDependente() {
        boolean saida = true;

        if (tf_dtn_Dependente.getText().trim().length() < 6) {
            saida = false;
        }

        return saida;
    }

    private boolean validaRgDependente() {
        boolean saida = true;

        if (tf_rg_Dependente.getText().trim().length() < 10) {
            saida = false;
        }

        return saida;
    }

    private boolean validaCpfDependente() {
        boolean saida = true;

        if (tf_cpf_Dependente.getText().trim().length() < 11) {
            saida = false;
        }

        return saida;
    }

    private boolean Validacao() {
        boolean saida = true;

        try {

            if (!validaCodDependente()) {
                throw new Exception("Digite apenas valores Inteiros para CÓDIGO.");

            }

            if (!validaNomeDependente()) {
                throw new Exception("O NOME tem que ter no minimo 4 caracteres!!!");
            }

            if (!validaDtnDependente()) {
                throw new Exception("A DATA NASCIMENTO tem que ter 6 caracteres!!!");
            }

            if (!validaRgDependente()) {
                throw new Exception("O RG tem que ter 10 caracteres!!!");
            }

            if (!validaCpfDependente()) {
                throw new Exception("O CPF tem que ter 11 caracteres!!!");
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de Validação de Campos: " + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private void LimparCampos() {

        tf_cd_Dependente.setText(null);
        tf_nm_Dependente.setText(null);
        tf_dtn_Dependente.setText(null);
        tf_rg_Dependente.setText(null);
        tf_cpf_Dependente.setText(null);

    }

}////////////////////
