/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author FO
 */
public class fr_Cad_GrauParentesco extends javax.swing.JFrame {

    private Tab_GrauParentesco tab_grauParentesco;
    private fr_Relatorio_GrauParentesco local_fr_Relatorio_GrauParentesco;

    private ArrayList<Tab_GrauParentesco> lista_tab_grauParentesco = new ArrayList();

    private int cod;

    /**
     * Creates new form fr_Cad_GrauParentesco
     */
    public fr_Cad_GrauParentesco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cd_GrauParentesco = new javax.swing.JLabel();
        tf_cd_GrauParentesco = new javax.swing.JTextField();
        lb_ds_GrauParentesco = new javax.swing.JLabel();
        bt_Limpar_GrauParentesco = new javax.swing.JButton();
        bt_valida_GrauParentesco = new javax.swing.JButton();
        cb_ds_GrauParentesco = new javax.swing.JComboBox<>();
        bt_Relatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadasro de Grau Parentesco");

        lb_cd_GrauParentesco.setText("Código:");

        lb_ds_GrauParentesco.setText("Grau Parentesco:");

        bt_Limpar_GrauParentesco.setText("Limpar");
        bt_Limpar_GrauParentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Limpar_GrauParentescoActionPerformed(evt);
            }
        });

        bt_valida_GrauParentesco.setText("Valida");
        bt_valida_GrauParentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_valida_GrauParentescoActionPerformed(evt);
            }
        });

        cb_ds_GrauParentesco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_ds_GrauParentesco.setSelectedIndex(-1);

        bt_Relatorio.setText("Relatório");
        bt_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_Limpar_GrauParentesco)
                        .addGap(18, 18, 18)
                        .addComponent(bt_valida_GrauParentesco)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Relatorio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_ds_GrauParentesco)
                            .addComponent(lb_cd_GrauParentesco))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_ds_GrauParentesco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_cd_GrauParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cd_GrauParentesco)
                    .addComponent(tf_cd_GrauParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ds_GrauParentesco)
                    .addComponent(cb_ds_GrauParentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar_GrauParentesco)
                    .addComponent(bt_valida_GrauParentesco)
                    .addComponent(bt_Relatorio))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Limpar_GrauParentescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Limpar_GrauParentescoActionPerformed
        LimparCampos();
    }//GEN-LAST:event_bt_Limpar_GrauParentescoActionPerformed

    private void bt_valida_GrauParentescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_valida_GrauParentescoActionPerformed
        Carrega_GrauParentesco();
        if (Validacao()) {

            LimparCampos();

        }
    }//GEN-LAST:event_bt_valida_GrauParentescoActionPerformed

    private void bt_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RelatorioActionPerformed
       if(!lista_tab_grauParentesco.isEmpty()) {
                
            local_fr_Relatorio_GrauParentesco =  new fr_Relatorio_GrauParentesco ();
            local_fr_Relatorio_GrauParentesco.MontaRelatorio_GrauParentesco(lista_tab_grauParentesco);
            local_fr_Relatorio_GrauParentesco.setVisible(true);
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Sem Registros para Exibir", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_bt_RelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_GrauParentesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_GrauParentesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_GrauParentesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_GrauParentesco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Cad_GrauParentesco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Limpar_GrauParentesco;
    private javax.swing.JButton bt_Relatorio;
    private javax.swing.JButton bt_valida_GrauParentesco;
    private javax.swing.JComboBox<String> cb_ds_GrauParentesco;
    private javax.swing.JLabel lb_cd_GrauParentesco;
    private javax.swing.JLabel lb_ds_GrauParentesco;
    private javax.swing.JTextField tf_cd_GrauParentesco;
    // End of variables declaration//GEN-END:variables

    private boolean validaCodGrauPar() {
        boolean saida = true;

        try {
            cod = Integer.parseInt(tf_cd_GrauParentesco.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros para CÓDIGO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private boolean Validacao() {
        boolean saida = true;

        try {

            if (!validaCodGrauPar()) {
                throw new Exception("Digite apenas valores Inteiros para CÓDIGO.");

            }
            if (cb_ds_GrauParentesco.getSelectedIndex() == -1) {
                throw new Exception("Selecione UM Grau para o Dependente.");
            }
            lista_tab_grauParentesco.add(tab_grauParentesco);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de Validação de Campos: " + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private void Carrega_GrauParentesco() {

        try {
            cod = Integer.parseInt(tf_cd_GrauParentesco.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros em CÓDIGO. ", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        tab_grauParentesco = new Tab_GrauParentesco();

        tab_grauParentesco.setCod_GrauParentesco(cod);

        tab_grauParentesco.setDs_GrauParentesco(cb_ds_GrauParentesco.getSelectedItem().toString());

    }

    private void LimparCampos() {

        tf_cd_GrauParentesco.setText(null);
        cb_ds_GrauParentesco.setSelectedIndex(-1);

    }

}/////////////////////////////
