/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author FO
 */
public class fr_Cad_Dependente extends javax.swing.JFrame {

    private Tab_Dependente tab_dependente;
    private fr_Relatorio_Dependente local_fr_Relatorio_Dependente;

    private ArrayList<Tab_Dependente> lista_tab_dependente = new ArrayList();
    private int cod;

    /**
     * Creates new form fr_Cad_Dependente
     */
    public fr_Cad_Dependente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cd_Dependente = new javax.swing.JLabel();
        tf_cd_Dependente = new javax.swing.JTextField();
        lb_func_Dependente = new javax.swing.JLabel();
        lb_nm_Dependente = new javax.swing.JLabel();
        tf_nm_Dependente = new javax.swing.JTextField();
        lb_dtn_Dependente = new javax.swing.JLabel();
        tf_dtn_Dependente = new javax.swing.JTextField();
        lb_rg_Dependente = new javax.swing.JLabel();
        tf_rg_Dependente = new javax.swing.JTextField();
        lb_cpf_Dependente = new javax.swing.JLabel();
        tf_cpf_Dependente = new javax.swing.JTextField();
        lb_gen_Dependente = new javax.swing.JLabel();
        lb_graupar_Dependente = new javax.swing.JLabel();
        bt_Limpar_Dependente = new javax.swing.JButton();
        bt_valida_Dependente = new javax.swing.JButton();
        cb_GrauParentescoDependente = new javax.swing.JComboBox<>();
        cb_GeneroDependente = new javax.swing.JComboBox<>();
        bt_Relatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Dependente");

        lb_cd_Dependente.setText("Código:");

        lb_func_Dependente.setText("Dep. Funcionario: ( FK)");

        lb_nm_Dependente.setText("Nome:");

        lb_dtn_Dependente.setText("Data Nascimento: 8");

        lb_rg_Dependente.setText("RG: 9");

        lb_cpf_Dependente.setText("CPF: 11");

        lb_gen_Dependente.setText("Genero: (FK)");

        lb_graupar_Dependente.setText("Grau Parentesco: (FK)");

        bt_Limpar_Dependente.setText("Limpar");
        bt_Limpar_Dependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Limpar_DependenteActionPerformed(evt);
            }
        });

        bt_valida_Dependente.setText("Valida");
        bt_valida_Dependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_valida_DependenteActionPerformed(evt);
            }
        });

        cb_GrauParentescoDependente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_GrauParentescoDependente.setSelectedIndex(-1);
        cb_GrauParentescoDependente.setToolTipText("");

        cb_GeneroDependente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_GeneroDependente.setSelectedIndex(-1);
        cb_GeneroDependente.setToolTipText("");

        bt_Relatorio.setText("Relatório");
        bt_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_Limpar_Dependente)
                    .addComponent(lb_func_Dependente)
                    .addComponent(lb_cd_Dependente)
                    .addComponent(lb_nm_Dependente)
                    .addComponent(lb_dtn_Dependente)
                    .addComponent(lb_rg_Dependente)
                    .addComponent(lb_cpf_Dependente)
                    .addComponent(lb_gen_Dependente)
                    .addComponent(lb_graupar_Dependente))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bt_valida_Dependente)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Relatorio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nm_Dependente, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(tf_cd_Dependente, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(tf_dtn_Dependente, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(tf_rg_Dependente, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(tf_cpf_Dependente, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(cb_GrauParentescoDependente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_GeneroDependente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cd_Dependente)
                    .addComponent(tf_cd_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_func_Dependente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nm_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nm_Dependente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dtn_Dependente)
                    .addComponent(tf_dtn_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_rg_Dependente)
                    .addComponent(tf_rg_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cpf_Dependente)
                    .addComponent(tf_cpf_Dependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_gen_Dependente)
                    .addComponent(cb_GeneroDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_graupar_Dependente)
                    .addComponent(cb_GrauParentescoDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar_Dependente)
                    .addComponent(bt_valida_Dependente)
                    .addComponent(bt_Relatorio))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Limpar_DependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Limpar_DependenteActionPerformed
        LimparCampos();
    }//GEN-LAST:event_bt_Limpar_DependenteActionPerformed

    private void bt_valida_DependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_valida_DependenteActionPerformed
        Carrega_TabDependnete();
        if (Validacao()) {

            LimparCampos();

        }
    }//GEN-LAST:event_bt_valida_DependenteActionPerformed

    private void bt_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RelatorioActionPerformed
        if(!lista_tab_dependente.isEmpty()) {
                
            local_fr_Relatorio_Dependente =  new fr_Relatorio_Dependente ();
            local_fr_Relatorio_Dependente.MontaRelatorio_Dependente(lista_tab_dependente);
            local_fr_Relatorio_Dependente.setVisible(true);
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Sem Registros para Exibir", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_bt_RelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Cad_Dependente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Limpar_Dependente;
    private javax.swing.JButton bt_Relatorio;
    private javax.swing.JButton bt_valida_Dependente;
    private javax.swing.JComboBox<String> cb_GeneroDependente;
    private javax.swing.JComboBox<String> cb_GrauParentescoDependente;
    private javax.swing.JLabel lb_cd_Dependente;
    private javax.swing.JLabel lb_cpf_Dependente;
    private javax.swing.JLabel lb_dtn_Dependente;
    private javax.swing.JLabel lb_func_Dependente;
    private javax.swing.JLabel lb_gen_Dependente;
    private javax.swing.JLabel lb_graupar_Dependente;
    private javax.swing.JLabel lb_nm_Dependente;
    private javax.swing.JLabel lb_rg_Dependente;
    private javax.swing.JTextField tf_cd_Dependente;
    private javax.swing.JTextField tf_cpf_Dependente;
    private javax.swing.JTextField tf_dtn_Dependente;
    private javax.swing.JTextField tf_nm_Dependente;
    private javax.swing.JTextField tf_rg_Dependente;
    // End of variables declaration//GEN-END:variables

    private boolean validaCodDependente() {
        boolean saida = true;

        try {
            cod = Integer.parseInt(tf_cd_Dependente.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros para CÓDIGO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private boolean validaNomeDependente() {
        boolean saida = true;

        if (tf_nm_Dependente.getText().trim().length() < 4) {
            saida = false;
        }

        return saida;
    }

    private boolean validaDtnDependente() {
        boolean saida = true;

        if (tf_dtn_Dependente.getText().trim().length() < 8) {
            saida = false;
        }

        return saida;
    }

    private boolean validaRgDependente() {
        boolean saida = true;

        if (tf_rg_Dependente.getText().trim().length() < 9) {
            saida = false;
        }

        return saida;
    }

    private boolean validaCpfDependente() {
        boolean saida = true;

        if (tf_cpf_Dependente.getText().trim().length() < 11) {
            saida = false;
        }

        return saida;
    }

    private boolean Validacao() {
        boolean saida = true;

        try {

            if (!validaCodDependente()) {
                throw new Exception("Digite apenas valores Inteiros para CÓDIGO.");

            }

            if (!validaNomeDependente()) {
                throw new Exception("O NOME tem que ter no minimo 4 caracteres!!!");
            }

            if (!validaDtnDependente()) {
                throw new Exception("A DATA NASCIMENTO tem que ter 6 caracteres!!!");
            }

            if (!validaRgDependente()) {
                throw new Exception("O RG tem que ter 10 caracteres!!!");
            }

            if (!validaCpfDependente()) {
                throw new Exception("O CPF tem que ter 11 caracteres!!!");
            }
            lista_tab_dependente.add(tab_dependente);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de Validação de Campos: " + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private void Carrega_TabDependnete() {

        try {
            cod = Integer.parseInt(tf_cd_Dependente.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros em CÓDIGO. ", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        tab_dependente = new Tab_Dependente();

        tab_dependente.setCod_Dependente(cod);

        tab_dependente.setNm_Dependente(tf_nm_Dependente.getText().trim());

        tab_dependente.setRg_Dependente(tf_rg_Dependente.getText().trim());
        tab_dependente.setCpf_Dependente(tf_cpf_Dependente.getText().trim());
        tab_dependente.setGen_Dependente(cb_GeneroDependente.getSelectedItem().toString());
        tab_dependente.setGrau_Parentesco_Dependente(cb_GrauParentescoDependente.getSelectedItem().toString());

    }

    private void LimparCampos() {

        tf_cd_Dependente.setText(null);
        tf_nm_Dependente.setText(null);
        tf_dtn_Dependente.setText(null);
        tf_rg_Dependente.setText(null);
        tf_cpf_Dependente.setText(null);
        cb_GeneroDependente.setSelectedIndex(-1);
        cb_GrauParentescoDependente.setSelectedIndex(-1);
        

    }

}////////////////////
