/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author FO
 */
public class fr_Cad_UF extends javax.swing.JFrame {

    private Tab_UF tab_uf;
    private fr_Relatorio_UF local_fr_Relatorio_UF;

    private ArrayList<Tab_UF> lista_tab_uf = new ArrayList();

    private int cod;

    /**
     * Creates new form fr_UF
     */
    public fr_Cad_UF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cod_UF = new javax.swing.JLabel();
        tf_cod_UF = new javax.swing.JTextField();
        lb_nm_UF = new javax.swing.JLabel();
        tf_nm_UF = new javax.swing.JTextField();
        lb_abr_UF = new javax.swing.JLabel();
        tf_abr_UF = new javax.swing.JTextField();
        bt_Limpar_UF = new javax.swing.JButton();
        bt_Valida_UF = new javax.swing.JButton();
        bt_Relatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de UF");

        lb_cod_UF.setText("Código:");

        lb_nm_UF.setText("Nome UF:");

        lb_abr_UF.setText("Abreviatura:");

        bt_Limpar_UF.setText("Limpar");
        bt_Limpar_UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Limpar_UFActionPerformed(evt);
            }
        });

        bt_Valida_UF.setText("Valida");
        bt_Valida_UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Valida_UFActionPerformed(evt);
            }
        });

        bt_Relatorio.setText("Relatório");
        bt_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt_Limpar_UF)
                            .addGap(28, 28, 28)
                            .addComponent(bt_Valida_UF)
                            .addGap(40, 40, 40)
                            .addComponent(bt_Relatorio))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lb_nm_UF)
                                .addComponent(lb_cod_UF))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_cod_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_nm_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_abr_UF)
                        .addGap(18, 18, 18)
                        .addComponent(tf_abr_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cod_UF)
                    .addComponent(tf_cod_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nm_UF)
                    .addComponent(tf_nm_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_abr_UF)
                    .addComponent(tf_abr_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar_UF)
                    .addComponent(bt_Valida_UF)
                    .addComponent(bt_Relatorio))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Limpar_UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Limpar_UFActionPerformed

        LimparCampos();
    }//GEN-LAST:event_bt_Limpar_UFActionPerformed

    private void bt_Valida_UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Valida_UFActionPerformed
        
        Carrega_TabUF();
        if (Validacao()) {

            LimparCampos();

        }

    }//GEN-LAST:event_bt_Valida_UFActionPerformed

    private void bt_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RelatorioActionPerformed
        if(!lista_tab_uf.isEmpty()) {
                
            local_fr_Relatorio_UF =  new fr_Relatorio_UF ();
            local_fr_Relatorio_UF.MontaRelatorio_UF(lista_tab_uf);
            local_fr_Relatorio_UF.setVisible(true);
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Sem Registros para Exibir", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_bt_RelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_UF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_UF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_UF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_UF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Cad_UF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Limpar_UF;
    private javax.swing.JButton bt_Relatorio;
    private javax.swing.JButton bt_Valida_UF;
    private javax.swing.JLabel lb_abr_UF;
    private javax.swing.JLabel lb_cod_UF;
    private javax.swing.JLabel lb_nm_UF;
    private javax.swing.JTextField tf_abr_UF;
    private javax.swing.JTextField tf_cod_UF;
    private javax.swing.JTextField tf_nm_UF;
    // End of variables declaration//GEN-END:variables

    private boolean validaCodUF() {
        boolean saida = true;

        try {
            cod = Integer.parseInt(tf_cod_UF.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros para CÓDIGO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private boolean validaNomeUF() {
        boolean saida = true;
        if (tf_nm_UF.getText().trim().length() < 4) {
            saida = false;
        }
        return saida;

    }

    private boolean validaAbrUF() {
        boolean saida = true;
        if ((tf_abr_UF.getText().trim().length() < 3) || (tf_abr_UF.getText().trim().length() > 3)) {
            saida = false;
        }
        return saida;

    }

    private boolean Validacao() {
        boolean saida = true;

        try {

            if (!validaCodUF()) {
                throw new Exception("Digite apenas valores Inteiros para CÓDIGO.");

            }

            if (!validaNomeUF()) {
                throw new Exception("O NOME tem que ter no minimo 4 caracteres!!!");
            }

            if (!validaAbrUF()) {
                throw new Exception("A ABREVIATURA tem que ter 3 caracteres!!!");
            }
            lista_tab_uf.add(tab_uf);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de Validação de Campos: " + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private void Carrega_TabUF() {

        try {
            cod = Integer.parseInt(tf_cod_UF.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros em CÓDIGO. ", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        tab_uf = new Tab_UF();

        tab_uf.setCod_UF(cod);

        tab_uf.setNm_UF(tf_nm_UF.getText().trim());

        tab_uf.setAbr_UF(tf_abr_UF.getText().trim());

    }

    private void LimparCampos() {
        tf_cod_UF.setText(null);
        tf_nm_UF.setText(null);
        tf_abr_UF.setText(null);

    }

}////////////////////////////////////////////////////////
