/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author FO
 */
public class fr_Cad_Tel_Celular extends javax.swing.JFrame {

    private Tab_Celular tab_celular;
    private fr_Relatorio_Celular local_fr_Relatorio_Celular;

    private ArrayList<Tab_Celular> lista_tab_Celular = new ArrayList();

    private int cod;
    private int nr;

    /**
     * Creates new form fr_Cad_Te_lCelular
     */
    public fr_Cad_Tel_Celular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cd_Tel_Celular = new javax.swing.JLabel();
        tf_cd_Tel_Celular = new javax.swing.JTextField();
        lb_nr_Tel_Celular = new javax.swing.JLabel();
        tf_nr_Tel_Celular = new javax.swing.JTextField();
        bt_Limpar_Tel_Celular = new javax.swing.JButton();
        bt_valida_Tel_Celular = new javax.swing.JButton();
        bt_Relatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Telefone Celular");

        lb_cd_Tel_Celular.setText("Código:");

        lb_nr_Tel_Celular.setText("Número:");

        bt_Limpar_Tel_Celular.setText("Limpar");
        bt_Limpar_Tel_Celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Limpar_Tel_CelularActionPerformed(evt);
            }
        });

        bt_valida_Tel_Celular.setText("Valida");
        bt_valida_Tel_Celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_valida_Tel_CelularActionPerformed(evt);
            }
        });

        bt_Relatorio.setText("Relatório");
        bt_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_nr_Tel_Celular)
                            .addComponent(lb_cd_Tel_Celular))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_cd_Tel_Celular, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(tf_nr_Tel_Celular)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bt_Limpar_Tel_Celular)
                        .addGap(27, 27, 27)
                        .addComponent(bt_valida_Tel_Celular)
                        .addGap(29, 29, 29)
                        .addComponent(bt_Relatorio)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cd_Tel_Celular)
                    .addComponent(tf_cd_Tel_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nr_Tel_Celular)
                    .addComponent(tf_nr_Tel_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar_Tel_Celular)
                    .addComponent(bt_valida_Tel_Celular)
                    .addComponent(bt_Relatorio))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Limpar_Tel_CelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Limpar_Tel_CelularActionPerformed
        LimparCampos();
    }//GEN-LAST:event_bt_Limpar_Tel_CelularActionPerformed

    private void bt_valida_Tel_CelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_valida_Tel_CelularActionPerformed
        Carrega_TabCelular();
        if (Validacao()) {

            LimparCampos();

        }// TODO add your handling code here:
    }//GEN-LAST:event_bt_valida_Tel_CelularActionPerformed

    private void bt_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RelatorioActionPerformed
        if (!lista_tab_Celular.isEmpty()) {
            local_fr_Relatorio_Celular = new fr_Relatorio_Celular();
            local_fr_Relatorio_Celular.MontaRelatorio_Celular(lista_tab_Celular);
            local_fr_Relatorio_Celular.setVisible(true);

        } else {

            JOptionPane.showMessageDialog(null, "Sem Registros para Exibir", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_RelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Tel_Celular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Tel_Celular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Tel_Celular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Tel_Celular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Cad_Tel_Celular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Limpar_Tel_Celular;
    private javax.swing.JButton bt_Relatorio;
    private javax.swing.JButton bt_valida_Tel_Celular;
    private javax.swing.JLabel lb_cd_Tel_Celular;
    private javax.swing.JLabel lb_nr_Tel_Celular;
    private javax.swing.JTextField tf_cd_Tel_Celular;
    private javax.swing.JTextField tf_nr_Tel_Celular;
    // End of variables declaration//GEN-END:variables

    private boolean validaCodTelCelular() {
        boolean saida = true;

        try {
            cod = Integer.parseInt(tf_cd_Tel_Celular.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros para CÓDIGO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private boolean validaNrTelCelular() {
        boolean saida = true;

        if (tf_nr_Tel_Celular.getText().trim().length() < 11) {
            saida = false;
        }

        return saida;
    }

    private boolean Validacao() {
        boolean saida = true;

        try {

            if (!validaCodTelCelular()) {
                throw new Exception("Digite apenas valores Inteiros para CÓDIGO.");

            }

            if (!validaNrTelCelular()) {
                throw new Exception("O NÚMERO DO CELULAR deve ter 11 Dígitos!!!");

            }
            lista_tab_Celular.add(tab_celular);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de Validação de Campos: " + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    public void Carrega_TabCelular() {

        try {
            cod = Integer.parseInt(tf_cd_Tel_Celular.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros em CÓDIGO. ", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        tab_celular = new Tab_Celular();

        tab_celular.setCod_Celular(cod);
        tab_celular.setNr_celular(tf_nr_Tel_Celular.getText().trim());

    }

    private void LimparCampos() {
        tf_cd_Tel_Celular.setText(null);
        tf_nr_Tel_Celular.setText(null);
    }

}////////////////////////////////
