/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author FO
 */
public class fr_Cad_Funcionario extends javax.swing.JFrame {
    
    private Tab_Funcionario tab_funcionario;
    private fr_Relatorio_Funcionario local_fr_Relatorio_Funcionario;

    private ArrayList<Tab_Funcionario> lista_tab_funcionario = new ArrayList();

    private int cod;

    /**
     * Creates new form fr_Cad_Funcionario
     */
    public fr_Cad_Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cd_Funcionario = new javax.swing.JLabel();
        tf_cd_Funcionario = new javax.swing.JTextField();
        lb_nm_Funcionario = new javax.swing.JLabel();
        tf_nm_Funcionario = new javax.swing.JTextField();
        lb_dtn_Funcionario = new javax.swing.JLabel();
        tf_dtn_Funcionario = new javax.swing.JTextField();
        lb_rg_Funcionario = new javax.swing.JLabel();
        tf_rg_Funcionario = new javax.swing.JTextField();
        lb_cpf_Funcionario = new javax.swing.JLabel();
        tf_cpf_Funcionario = new javax.swing.JTextField();
        lb_end_Funcionario = new javax.swing.JLabel();
        lb_cid_funcioanrio = new javax.swing.JLabel();
        lb_gen_Funcionario = new javax.swing.JLabel();
        lb_derp_Funcionario = new javax.swing.JLabel();
        lb_carg_Funcionario = new javax.swing.JLabel();
        bt_Limpar_Funcionario = new javax.swing.JButton();
        bt_valida_Funcionario = new javax.swing.JButton();
        bt_Relatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionário");

        lb_cd_Funcionario.setText("Código:");

        lb_nm_Funcionario.setText("Nome:");

        lb_dtn_Funcionario.setText("Data Nascimento: 8");

        lb_rg_Funcionario.setText("RG: 9");

        lb_cpf_Funcionario.setText("CPF: 11");

        lb_end_Funcionario.setText("Endereço: (FK)");

        lb_cid_funcioanrio.setText("Cidade: (FK)");

        lb_gen_Funcionario.setText("Genero: (FK)");

        lb_derp_Funcionario.setText("Departamento: (FK)");

        lb_carg_Funcionario.setText("Cargo: (FK)");

        bt_Limpar_Funcionario.setText("Limpar");
        bt_Limpar_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Limpar_FuncionarioActionPerformed(evt);
            }
        });

        bt_valida_Funcionario.setText("Valida");
        bt_valida_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_valida_FuncionarioActionPerformed(evt);
            }
        });

        bt_Relatorio.setText("Relatório");
        bt_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_end_Funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_cid_funcioanrio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_gen_Funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_derp_Funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_carg_Funcionario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bt_Limpar_Funcionario)
                                .addGap(27, 27, 27)
                                .addComponent(bt_valida_Funcionario)
                                .addGap(29, 29, 29)
                                .addComponent(bt_Relatorio))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_nm_Funcionario)
                            .addComponent(lb_dtn_Funcionario)
                            .addComponent(lb_rg_Funcionario)
                            .addComponent(lb_cpf_Funcionario)
                            .addComponent(lb_cd_Funcionario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_cd_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_rg_Funcionario, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                .addComponent(tf_dtn_Funcionario)
                                .addComponent(tf_cpf_Funcionario)
                                .addComponent(tf_nm_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cd_Funcionario)
                    .addComponent(tf_cd_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nm_Funcionario)
                    .addComponent(tf_nm_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dtn_Funcionario)
                    .addComponent(tf_dtn_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_rg_Funcionario)
                    .addComponent(tf_rg_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cpf_Funcionario)
                    .addComponent(tf_cpf_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_end_Funcionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_cid_funcioanrio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_gen_Funcionario)
                .addGap(18, 18, 18)
                .addComponent(lb_derp_Funcionario)
                .addGap(18, 18, 18)
                .addComponent(lb_carg_Funcionario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar_Funcionario)
                    .addComponent(bt_valida_Funcionario)
                    .addComponent(bt_Relatorio))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Limpar_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Limpar_FuncionarioActionPerformed
        LimparCampos();
    }//GEN-LAST:event_bt_Limpar_FuncionarioActionPerformed

    private void bt_valida_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_valida_FuncionarioActionPerformed
        Carrega_TabFuncionario();
        if (Validacao()) {

            LimparCampos();

        }// TODO add your handling code here:
    }//GEN-LAST:event_bt_valida_FuncionarioActionPerformed

    private void bt_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RelatorioActionPerformed
        if(!lista_tab_funcionario.isEmpty()) {
                
            local_fr_Relatorio_Funcionario =  new fr_Relatorio_Funcionario ();
            local_fr_Relatorio_Funcionario.MontaRelatorio_Funcionario(lista_tab_funcionario);
            local_fr_Relatorio_Funcionario.setVisible(true);
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Sem Registros para Exibir", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_bt_RelatorioActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Funcionario.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Funcionario.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Funcionario.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Funcionario.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Cad_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Limpar_Funcionario;
    private javax.swing.JButton bt_Relatorio;
    private javax.swing.JButton bt_valida_Funcionario;
    private javax.swing.JLabel lb_carg_Funcionario;
    private javax.swing.JLabel lb_cd_Funcionario;
    private javax.swing.JLabel lb_cid_funcioanrio;
    private javax.swing.JLabel lb_cpf_Funcionario;
    private javax.swing.JLabel lb_derp_Funcionario;
    private javax.swing.JLabel lb_dtn_Funcionario;
    private javax.swing.JLabel lb_end_Funcionario;
    private javax.swing.JLabel lb_gen_Funcionario;
    private javax.swing.JLabel lb_nm_Funcionario;
    private javax.swing.JLabel lb_rg_Funcionario;
    private javax.swing.JTextField tf_cd_Funcionario;
    private javax.swing.JTextField tf_cpf_Funcionario;
    private javax.swing.JTextField tf_dtn_Funcionario;
    private javax.swing.JTextField tf_nm_Funcionario;
    private javax.swing.JTextField tf_rg_Funcionario;
    // End of variables declaration//GEN-END:variables

    private boolean validaCodFuncionario() {
        boolean saida = true;

        try {
            cod = Integer.parseInt(tf_cd_Funcionario.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros para CÓDIGO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private boolean validaNomeFuncionario() {
        boolean saida = true;

        if (tf_nm_Funcionario.getText().trim().length() < 4) {
            saida = false;
        }

        return saida;
    }

    private boolean validaDtnFuncionario() {
        boolean saida = true;

        if (tf_dtn_Funcionario.getText().trim().length() < 8) {
            saida = false;
        }

        return saida;
    }

    private boolean validaRgFuncionario() {
        boolean saida = true;

        if (tf_rg_Funcionario.getText().trim().length() < 9) {
            saida = false;
        }

        return saida;
    }

    private boolean validaCpfFuncionario() {
        boolean saida = true;

        if (tf_cpf_Funcionario.getText().trim().length() < 11) {
            saida = false;
        }

        return saida;
    }

    private boolean Validacao() {
        boolean saida = true;

        try {

            if (!validaCodFuncionario()) {
                throw new Exception("Digite apenas valores Inteiros para CÓDIGO.");

            }

            if (!validaNomeFuncionario()) {
                throw new Exception("O NOME tem que ter no minimo 4 caracteres!!!");
            }

            if (!validaDtnFuncionario()) {
                throw new Exception("A DATA NASCIMENTO tem que ter 6 caracteres!!!");
            }

            if (!validaRgFuncionario()) {
                throw new Exception("O RG tem que ter 10 caracteres!!!");
            }

            if (!validaCpfFuncionario()) {
                throw new Exception("O CPF tem que ter 11 caracteres!!!");
            }
            lista_tab_funcionario.add(tab_funcionario);

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de Validação de Campos: " + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }
    
    public void Carrega_TabFuncionario(){
        
        try {
            cod = Integer.parseInt(tf_cd_Funcionario.getText().trim());
            
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros em CÓDIGO. ", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        tab_funcionario = new Tab_Cargo();

        tab_funcionario.setCod_Funcionario(cod);

        tab_funcionario.setNm_Funcionario(tf_nm_Funcionario.getText().trim());
        
        tab_funcionario.setDt_Nascimento(tf_dtn_Funcionario.getText().trim());
        
        tab_funcionario.setRg(tf_rg_Funcionario.getText().trim());
        
        tab_funcionario.setCpf(tf_cpf_Funcionario.getText().trim());
        
        //tab_funcionario.setDs_Endereco(tf_dtn_Funcionario.getText().trim());
        //tab_funcionario.setDs_Cidade()(tf_dtn_Funcionario.getText().trim());
        //tab_funcionario.setDs_Genero(tf_dtn_Funcionario.getText().trim());
        //tab_funcionario.setDs_Departamento(tf_dtn_Funcionario.getText().trim());
        //tab_funcionario.setDs_Ds_Cargo(tf_dtn_Funcionario.getText().trim());

         
    
    
    }

    private void LimparCampos() {

        tf_cd_Funcionario.setText(null);
        tf_nm_Funcionario.setText(null);
        tf_dtn_Funcionario.setText(null);
        tf_rg_Funcionario.setText(null);
        tf_cpf_Funcionario.setText(null);

    }

}///////////////////////////////////
