/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author FO
 */
public class fr_Cad_Cargo extends javax.swing.JFrame {

    private Tab_Cargo tab_cargo;
    private fr_Relatorio_Cargo local_fr_Relatorio_Cargo;

    private ArrayList<Tab_Cargo> lista_tab_cargo = new ArrayList();

    private int cod;
    private double salario;

    /**
     * Creates new form fr_Cad_Cargo
     */
    public fr_Cad_Cargo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_cd_Cargo = new javax.swing.JLabel();
        tf_cd_Cargo = new javax.swing.JTextField();
        lb_nm_Cargo = new javax.swing.JLabel();
        tf_nm_Cargo = new javax.swing.JTextField();
        lb_ds_Cargo = new javax.swing.JLabel();
        tf_ds_Cargo = new javax.swing.JTextField();
        lb_sal_Cargo = new javax.swing.JLabel();
        tf_sal_Cargo = new javax.swing.JTextField();
        bt_Limpar_Cargo = new javax.swing.JButton();
        bt_valida_Cargo = new javax.swing.JButton();
        bt_Relatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cargo");

        lb_cd_Cargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_cd_Cargo.setText("Código:");

        tf_cd_Cargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lb_nm_Cargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_nm_Cargo.setText("Nome:");

        tf_nm_Cargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lb_ds_Cargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_ds_Cargo.setText("Descrição:");

        tf_ds_Cargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lb_sal_Cargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_sal_Cargo.setText("Salário:");

        tf_sal_Cargo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        bt_Limpar_Cargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_Limpar_Cargo.setText("Limpar");
        bt_Limpar_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Limpar_CargoActionPerformed(evt);
            }
        });

        bt_valida_Cargo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_valida_Cargo.setText("Valida");
        bt_valida_Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_valida_CargoActionPerformed(evt);
            }
        });

        bt_Relatorio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt_Relatorio.setText("Relatório");
        bt_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_Limpar_Cargo)
                                .addGap(28, 28, 28)
                                .addComponent(bt_valida_Cargo)
                                .addGap(18, 18, 18)
                                .addComponent(bt_Relatorio))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lb_sal_Cargo)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_sal_Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lb_cd_Cargo)
                                        .addComponent(lb_nm_Cargo))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_cd_Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(tf_nm_Cargo))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lb_ds_Cargo)
                        .addGap(18, 18, 18)
                        .addComponent(tf_ds_Cargo)))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_cd_Cargo)
                    .addComponent(tf_cd_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nm_Cargo)
                    .addComponent(tf_nm_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ds_Cargo)
                    .addComponent(tf_ds_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_sal_Cargo)
                    .addComponent(tf_sal_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Limpar_Cargo)
                    .addComponent(bt_valida_Cargo)
                    .addComponent(bt_Relatorio))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Limpar_CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Limpar_CargoActionPerformed

        LimparCampos();
    }//GEN-LAST:event_bt_Limpar_CargoActionPerformed

    private void bt_valida_CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_valida_CargoActionPerformed
        
        Carrega_TabCargo();
        if (Validacao()) {

            LimparCampos();

        }// TODO add your handling code here:
    }//GEN-LAST:event_bt_valida_CargoActionPerformed

    private void bt_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RelatorioActionPerformed
        if(!lista_tab_cargo.isEmpty()) {
                
            local_fr_Relatorio_Cargo =  new fr_Relatorio_Cargo ();
            local_fr_Relatorio_Cargo.MontaRelatorio_Cargo(lista_tab_cargo);
            local_fr_Relatorio_Cargo.setVisible(true);
            
        } else {
            
            JOptionPane.showMessageDialog(null, "Sem Registros para Exibir", "Erro", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_bt_RelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Cad_Cargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Cad_Cargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Limpar_Cargo;
    private javax.swing.JButton bt_Relatorio;
    private javax.swing.JButton bt_valida_Cargo;
    private javax.swing.JLabel lb_cd_Cargo;
    private javax.swing.JLabel lb_ds_Cargo;
    private javax.swing.JLabel lb_nm_Cargo;
    private javax.swing.JLabel lb_sal_Cargo;
    private javax.swing.JTextField tf_cd_Cargo;
    private javax.swing.JTextField tf_ds_Cargo;
    private javax.swing.JTextField tf_nm_Cargo;
    private javax.swing.JTextField tf_sal_Cargo;
    // End of variables declaration//GEN-END:variables

    private boolean validaCodCargo() {
        boolean saida = true;

        try {
            cod = Integer.parseInt(tf_cd_Cargo.getText().trim());
            
        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros para CÓDIGO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private boolean validaNomeCargo() {
        boolean saida = true;

        if (tf_nm_Cargo.getText().trim().length() < 4) {
            saida = false;
        }

        return saida;
    }

    private boolean validaDsCargo() {
        boolean saida = true;
        if ((tf_ds_Cargo.getText().trim().length() < 3)) {
            saida = false;
        }
        return saida;

    }

    private boolean validaSalCargo() {
        boolean saida = true;

        try {
            salario = Double.parseDouble(tf_sal_Cargo.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas NÚMEROS para SALÁRIO.", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private void Carrega_TabCargo() {

        try {
            cod = Integer.parseInt(tf_cd_Cargo.getText().trim());
            salario = Double.parseDouble(tf_sal_Cargo.getText().trim());

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores Inteiros em CÓDIGO. ", "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        tab_cargo = new Tab_Cargo();

        tab_cargo.setCod_cargo(cod);

        tab_cargo.setNm_cargo(tf_nm_Cargo.getText().trim());

        tab_cargo.setDs_cargo(tf_ds_Cargo.getText().trim());
        tab_cargo.setSalario_cargo(salario);

    }

    private boolean Validacao() {
        boolean saida = true;

        try {

            if (!validaCodCargo()) {
                throw new Exception("Digite apenas valores Inteiros para CÓDIGO.");

            }
            if (!validaNomeCargo()) {
                throw new Exception("O NOME tem que ter no minimo 4 caracteres!!!");
            }
            if (!validaDsCargo()) {
                throw new Exception("A DESCRIÇÃO tem que ter 3 caracteres!!!");
            }

            if (!validaSalCargo()) {
                throw new Exception("Digite apenas NÚMEROS para SALÁRIO!!!");
            }
            
            lista_tab_cargo.add(tab_cargo);
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro de Validação de Campos: " + erro.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);

        }

        return saida;
    }

    private void LimparCampos() {
        tf_cd_Cargo.setText(null);
        tf_ds_Cargo.setText(null);
        tf_nm_Cargo.setText(null);
        tf_sal_Cargo.setText(null);

    }

}///////////////////////////////
