/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_funcionario_2022.pkg;

import java.util.ArrayList;

/**
 *
 * @author FO
 */
public class fr_Relatorio_Dependente extends javax.swing.JFrame {

    /**
     * Creates new form fr_Relatorio_Dependente
     */
    public fr_Relatorio_Dependente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Relatorio_Dependente = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório Dependente");

        ta_Relatorio_Dependente.setColumns(20);
        ta_Relatorio_Dependente.setRows(5);
        jScrollPane1.setViewportView(ta_Relatorio_Dependente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_Relatorio_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_Relatorio_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_Relatorio_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_Relatorio_Dependente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_Relatorio_Dependente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_Relatorio_Dependente;
    // End of variables declaration//GEN-END:variables

    public void MontaRelatorio_Dependente(ArrayList<Tab_Dependente> lista_tab_dependente) {

        String msg = "Relatório Dependente\n";

        for (int i = 0; i < lista_tab_dependente.size(); i++) {

            msg = msg + "\nCódigo.......:  " + lista_tab_dependente.get(i).getCod_Dependente();
            //msg = msg + "\nDep. Funcionario: ( FK)..: " + lista_tab_dependente.get(i).getDs_cargo().toUpperCase();
            msg = msg + "\nNome.........:  " + lista_tab_dependente.get(i).getNm_Dependente().toUpperCase();
            msg = msg + "\nData Nascimento:........:  " + lista_tab_dependente.get(i).getDt_NasDependente();
            msg = msg + "\nRG........:  " + lista_tab_dependente.get(i).getRg_Dependente();
            msg = msg + "\nCPF........:  " + lista_tab_dependente.get(i).getCpf_Dependente();
            msg = msg + "\nGenero: (FK):........:  " + lista_tab_dependente.get(i).getGen_Dependente();
            msg = msg + "\nGrau Parentesco: (FK):........:  " + lista_tab_dependente.get(i).getGrau_Parentesco_Dependente();
            msg = msg + "\n----------------------------------------------------";

        }
        
        ta_Relatorio_Dependente.setText(msg);
    
    }

}
